#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
test:
  clients:
    type: local
    number: 2
  rounds:
  - label: init
    txDuration:
    - 25
    rateControl:
    - type: fixed-rate
      opts:
        tps: 10
    callback: benchmarks/samples/fabric/marbles/init.js

monitor:
  interval: 1
  type:
  - docker
  - process
  # - prometheus
  docker:
    name:
    - all
  process:
  - command: node
    arguments: fabricClientWorker.js
    multiOutput: avg
  # prometheus:
  #   url: "http://localhost:9090"
  #   push_url: "http://localhost:9091"
  #   metrics:
  #     ignore: [prometheus, pushGateway, cadvisor,  grafana, node-exporter]
  #     include:
  #       CPU% (Av):
  #           query: sum(rate(container_cpu_usage_seconds_total{name=~".+"}[5m])) by (name) * 100
  #           label: name
  #           step: 10
  #           statistic: avg
  #       CPU% (max):
  #           query: sum(rate(container_cpu_usage_seconds_total{name=~".+"}[5m])) by (name) * 100
  #           label: name
  #           step: 10
  #           statistic: max
  #       Memory (MB):
  #           query: sum(container_memory_rss{name=~".+"}) by (name)
  #           label: name
  #           step: 10
  #           statistic: avg
  #           multiplier: 0.000001
  #       Endorse Time (s):
  #           query: rate(endorser_propsal_duration_sum{chaincode="marbles:v0"}[5m])/rate(endorser_propsal_duration_count{chaincode="marbles:v0"}[5m])
  #           label: instance
  #           step: 1
  #           statistic: avg

