---
test:
  name: smallbank
  description: This is smallbank benchmark for caliper
  clients:
    type: local
    number: 5
  rounds:
  - label: smallOperations
    txNumber:
    - 500
    rateControl:
    - type: fixed-rate
      opts:
        tps: 20
    arguments:
      accounts: 400
      txnPerBatch: 1
    callback: benchmarks/scenario/smallbank/smallbankOperations.js
  - label: query
    txNumber:
    - 500
    rateControl:
    - type: fixed-rate
      opts:
        tps: 50
    callback: benchmarks/scenario/smallbank/query.js
observer:
  type: prometheus
  interval: 5
monitor:
  interval: 1
  type:
  - docker
  - process
  - prometheus
  docker:
    name:
    - all
  process:
  - command: node
    arguments: fabricClientWorker.js
    multiOutput: avg
  prometheus:
    url: "http://localhost:9090"
    push_url: "http://localhost:9091"
    metrics:
      ignore: [prometheus, pushGateway, cadvisor,  grafana, node-exporter]
      include:
        CPU% (Av):
            query: sum(rate(container_cpu_usage_seconds_total{name=~".+"}[5m])) by (name) * 100
            label: name
            step: 10
            statistic: avg
        CPU% (max):
            query: sum(rate(container_cpu_usage_seconds_total{name=~".+"}[5m])) by (name) * 100
            label: name
            step: 10
            statistic: max
        Memory (MB):
            query: sum(container_memory_rss{name=~".+"}) by (name)
            label: name
            step: 10
            statistic: avg
            multiplier: 0.000001