name: Test Chaincodes and Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc-env: [go, java, node]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: .github/scripts/run-fabric-tests.sh ${{ matrix.cc-env }}
